import './globals.css'
import { Poppins } from 'next/font/google'
import LayoutProvider from './layoutProvider';

const poppins = Poppins({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'mari belajar next',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gray-100`}>
        <LayoutProvider>
          {children}
        </LayoutProvider>
      </body>
    </html>
  );
}
